name: Deploy Frontend
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Deploy artifacts
        run: |
          echo 'listing ls'
          ls
          echo 'listing public bf'
          ls public
          mkdir public/dest
          echo 'listing public after'
          ls public
          cp -r ./src/ ./public/dest/
          echo 'listing public/dest/---------'
          ls public/dest/
