name: Deploy Frontend
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Deploy artifacts
        run: |
          ls
          ls public
          mkdir public/dest
          ls public
          cp src public/dest/
